In [8]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv("AB_NYC_2019.csv")

In [10]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0

In [11]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150.0,3.0,0.0,NaN,NaN,1.0,365.0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0

In [12]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,7.391000e+03,7.391000e+03,7391.000000,7391.000000,7390.000000,7390.000000,7390.000000,6567.000000,7390.000000,7390.000000
mean,2.443569e+06,7.922206e+06,40.729248,-73.950496,167.145873,8.530717,50.785792,0.897995,2.636130,133.241678
std,1.689463e+06,7.639974e+06,0.051749,0.779693,278.992369,29.761734,72.709536,1.133974,6.907491,138.350376
min,2.539000e+03,2.571000e+03,40.508680,-74.239860,10.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,8.227680e+05,1.599930e+06,40.688775,-73.984005,80.000000,2.000000,4.000000,0.130000,1.000000,0.000000
50%,2.224896e+06,5.076827e+06,40.723220,-73.959300,120.000000,3.000000,18.000000,0.420000,1.000000,81.000000
75%,4.032019e+06,1.198219e+07,40.763785,-73.943620,185.000000,5.000000,67.000000,1.250000,2.000000,273.000000
max,5.478741e+06,4.139808e+07,40.908040,-7.000000,9999.000000,1250.000000,607.000000,13.450000,96.000000,365.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7391 entries, 0 to 7390
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              7391 non-null   int64
 1   name                            7384 non-null   object
 2   host_id                         7391 non-null   int64
 3   host_name                       7386 non-null   object
 4   neighbourhood_group             7391 non-null   object
 5   neighbourhood                   7391 non-null   object
 6   latitude                        7391 non-null   float64
 7   longitude                       7391 non-null   float64
 8   room_type                       7390 non-null   object
 9   price                           7390 non-null   float64
 10  minimum_nights                  7390 non-null   float64
 11  number_of_reviews               7390 non-null   float64
 12  last_review                     6567 non-null   object
 13  reviews_per_month               6567 non-null   float64
 14  calculated_host_listings_count  7390 non-null   float64
 15  availability_365                7390 non-null   float64
dtypes: float64(8), int64(2), object(6)
memory usage: 924.0+ KB

In [14]:
import pandas as pd
import numpy as np

In [15]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
id                                  0
name                                7
host_id                             0
host_name                           5
neighbourhood_group                 0
neighbourhood                       0
latitude                            0
longitude                           0
room_type                           1
price                               1
minimum_nights                      1
number_of_reviews                   1
last_review                       824
reviews_per_month                 824
calculated_host_listings_count      1
availability_365                    1
dtype: int64

In [16]:
df['name'].fillna(df['name'].mode()[0], inplace=True)
df['host_name'].fillna(df['host_name'].mode()[0], inplace=True)
df['room_type'].fillna(df['room_type'].mode()[0], inplace=True)

In [17]:
df['price'].fillna(df['price'].median(), inplace=True)
df['minimum_nights'].fillna(df['minimum_nights'].median(), inplace=True)
df['number_of_reviews'].fillna(df['number_of_reviews'].median(), inplace=True)
df['reviews_per_month'].fillna(df['reviews_per_month'].median(), inplace=True)
df['calculated_host_listings_count'].fillna(df['calculated_host_listings_count'].median(), inplace=True)
df['availability_365'].fillna(df['availability_365'].median(), inplace=True)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
z_scores = (df['price'] - df['price'].mean()) / df['price'].std()
outliers = df[(z_scores < -3) | (z_scores > 3)]
print("Number of outliers:", len(outliers))

Number of outliers: 50